### ISSUE TITLE
Add support for HTTPS

### ISSUE THREAD

**Issue by TheNiceGuy** [n1try/mininote#13]
I quickly tested this application and it works great! I didn't notice any information concerning HTTPS support? Is it planned? Thanks!

**Comment by n1try** [comment]
Hey @TheNiceGuy!
You're right, the application currently does not support HTTPS "natively". However, a good practice (which I am also using for my own instance) is to host MiniNote behind a `nginx` oder `Caddy` Reverse Proxy that handles encryption instead of directly exposing MiniNote's `Express` webserver directly to the public.
Anyway, it can't hurt to also include HTTPS support directly in the application and it shouldn't be too hard. If somebody is interested in implementing that, go for it :wink:

**Comment by n1try** [comment]
Resolved by #30
